apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 4
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: 844820972788.dkr.ecr.ap-northeast-1.amazonaws.com/dsuser-04-cluster-repo:650fe3023be35d5000e70eaf86cf2f2383a368c2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
