apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 6
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: 844820972788.dkr.ecr.ap-northeast-1.amazonaws.com/dsuser-04-cluster-repo:ba0221fdb2acda92d81b54169e12d8bfa6e7b840
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
